services:
#  qdrant:
#    image: qdrant/qdrant
#    ports:
#      - "6333:6333"
#      - "6334:6334"
#    volumes:
#      - ./qdrant_storage:/qdrant/storage:z
  app:
    build: ./backend
    container_name: "original_art_app"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${FAST_API_PORT}:3000"
    volumes:
      - "./backend:/code/fast"
    networks:
      - intern

  db:
    image: postgres:16.1-bullseye
    container_name: "original_art_db"
    restart: on-failure
    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432" # Postgres image port 5432

    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - intern

networks:
  intern:
    driver: bridge